#!/usr/bin/env bash
set -euo pipefail

# generate-copilot-instructions.sh — Memory Manager (deterministic, no LLM key)
# Reads .github/risk-gate.yml and generates .github/copilot-instructions.md
# so native Copilot Code Review enforces your repo's risk policy on every PR.
#
# Usage:
#   ./scripts/generate-copilot-instructions.sh [--config .github/risk-gate.yml] [--out .github/copilot-instructions.md] [--check]
#   --check: exit 1 if generated output differs from existing file (CI drift check)

CONFIG=".github/risk-gate.yml"
OUT=".github/copilot-instructions.md"
CHECK=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config) CONFIG="$2"; shift 2;;
    --out) OUT="$2"; shift 2;;
    --check) CHECK=true; shift;;
    --help|-h) sed -n '2,10p' "$0"; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

RISKY_PATHS=()
RISKY_PATTERNS=()
LABEL="needs-human-review"
COVERAGE_FLOOR="85"

if [[ -f "$CONFIG" ]]; then
  if command -v yq >/dev/null 2>&1; then
    LABEL=$(yq -r '.risk.label // "needs-human-review"' "$CONFIG")
    mapfile -t RISKY_PATHS < <(yq -r '.risk.risky_paths[]?' "$CONFIG")
    mapfile -t RISKY_PATTERNS < <(yq -r '.risk.risky_patterns[]?' "$CONFIG")
    COVERAGE_FLOOR=$(yq -r '.guardrails.coverage_floor // 85' "$CONFIG")
  else
    RISKY_PATHS=("api/**" "mcp/**" "auth/**" "src/design-system/**" "skills/**" ".opencode/**" "AGENTS.md" "**/migrations/**")
    RISKY_PATTERNS=('.*\.sql$')
  fi
else
  echo "warn: config $CONFIG not found, using defaults" >&2
  RISKY_PATHS=("api/**" "mcp/**" "auth/**" "src/design-system/**" "skills/**" ".opencode/**" "AGENTS.md" "**/migrations/**")
  RISKY_PATTERNS=('.*\.sql$')
fi

TMP_OUT=$(mktemp)
{
  printf '%s\n' '<!-- AUTO-GENERATED by scripts/generate-copilot-instructions.sh — do not hand-edit. -->'
  printf '%s\n' "<!-- Source: $CONFIG — re-run ./scripts/generate-copilot-instructions.sh after changing risk policy. -->"
  printf '%s\n' ''
  printf '%s\n' '# Copilot Code Review instructions (risk-gate mesh)'
  printf '%s\n' ''
  printf '%s\n' 'You are the Deep Code Reviewer. Focus on objective bugs. Do not restate the diff.'
  printf '%s\n' 'Human reviewers own system design judgment — you own correctness.'
  printf '%s\n' ''
  printf '%s\n' '## 1. Risk routing (authoritative)'
  printf '%s\n' ''
  printf '%s\n' "This repo uses deterministic risk gating. The [$LABEL] label is set by CI (risk-gate.sh):"
  printf '%s\n' ''
  printf '%s\n' "- If PR has label [$LABEL] → HIGH-RISK. Review deeply: correctness, security, data loss, auth, migrations."
  printf '%s\n' '- If PR has label [copilot-safe] (or no risk label) → LOW-RISK. Review for objective bugs only. Keep comments minimal.'
  printf '%s\n' ''
  printf '%s\n' 'High-risk paths (any match requires human review):'
  printf '%s\n' ''
  if [[ ${#RISKY_PATHS[@]} -eq 0 ]]; then
    printf '%s\n' '- (none configured)'
  else
    for p in "${RISKY_PATHS[@]}"; do printf '%s\n' "- $p"; done
  fi
  printf '%s\n' ''
  printf '%s\n' 'High-risk filename patterns (regex):'
  printf '%s\n' ''
  if [[ ${#RISKY_PATTERNS[@]} -eq 0 ]]; then
    printf '%s\n' '- (none configured)'
  else
    for r in "${RISKY_PATTERNS[@]}"; do printf '%s\n' "- $r"; done
  fi
  printf '%s\n' ''
  printf '%s\n' '## 2. Three review passes (run in order)'
  printf '%s\n' ''
  printf '%s\n' 'Run these as separate passes. Stop early on LOW-RISK PRs after Pass A unless something looks wrong.'
  printf '%s\n' ''
  printf '%s\n' '### Pass A — Plan conformance (highest signal)'
  printf '%s\n' ''
  printf '%s\n' 'The PR body must link a plan (Closes #N, Plan:/RFC:/Spec:, or a plans/ path — enforced by plan-link-gate).'
  printf '%s\n' 'Check: does the diff implement what the linked issue/plan says? Flag scope creep, missing'
  printf '%s\n' 'plan items, or behavior changes with no plan coverage. Business-logic deviations need'
  printf '%s\n' 'biz validation even if the code looks correct (the AI often "knows better" — still flag it).'
  printf '%s\n' 'If no plan is linked, say so in one line and skip to verdict.'
  printf '%s\n' ''
  printf '%s\n' '### Pass B — Bugs / correctness'
  printf '%s\n' ''
  printf '%s\n' 'Wrong logic, off-by-one, null handling, unhandled errors, races, broken imports.'
  printf '%s\n' 'Missing coverage for new branches. Floor is '"${COVERAGE_FLOOR}"' percent. Do not demand tests for docs or config-only PRs.'
  printf '%s\n' ''
  printf '%s\n' '### Pass C — Security (always run on HIGH-RISK PRs)'
  printf '%s\n' ''
  printf '%s\n' 'Auth bypass, injection, secrets in diff, broad permissions, SSRF or open redirect.'
  printf '%s\n' 'Data: destructive migrations, missing rollback, non-additive schema changes. Flag sql and migration files as high-risk.'
  printf '%s\n' ''
  printf '%s\n' '### Preview check (UI PRs)'
  printf '%s\n' ''
  printf '%s\n' 'If the diff touches UI paths, note whether a preview deploy/status is present.'
  printf '%s\n' 'Do not block for lack of one — just state: Preview present YES/NO. Manual end-to-end'
  printf '%s\n' 'verification happens there when needed.'
  printf '%s\n' ''
  printf '%s\n' '## 3. What NOT to do'
  printf '%s\n' ''
  printf '%s\n' '- Do not comment on formatting or lint (lint-gate handles it).'
  printf '%s\n' '- Do not suggest refactors or redesigns on low-risk PRs.'
  printf '%s\n' '- Leave a Comment review with file and line findings plus suggested fixes. Do not approve or block.'
  printf '%s\n' '- Keep findings to high and medium severity. Batch nits into one summary bullet at most.'
  printf '%s\n' ''
  printf '%s\n' '## 4. Response format'
  printf '%s\n' ''
  printf '%s\n' '- Start with one line: Risk HIGH or LOW plus one-sentence reason.'
  printf '%s\n' '- Then findings as: path/to/file line — what is wrong plus suggested fix.'
  printf '%s\n' '- End with: Safe to merge YES or NO plus condition.'
  printf '%s\n' ''
  printf '%s\n' '## 5. Repo guardrails (already enforced by CI, do not duplicate)'
  printf '%s\n' ''
  printf '%s\n' '- Plan link required on non-exempt PRs (plan-link-gate).'
  printf '%s\n' '- Docs markdown files must live under docs or .github (docs-gate).'
  printf '%s\n' '- skills, AGENTS.md and .opencode must ship in solo PRs (skills-isolation).'
  printf '%s\n' "Coverage floor ${COVERAGE_FLOOR} percent (coverage-gate), lint via ruff ty prettier eslint (lint-gate)."
} > "$TMP_OUT"

if [[ "$CHECK" == true ]]; then
  if [[ ! -f "$OUT" ]]; then
    echo "missing $OUT — run ./scripts/generate-copilot-instructions.sh" >&2
    rm -f "$TMP_OUT"
    exit 1
  fi
  if ! diff -u "$OUT" "$TMP_OUT"; then
    echo "drift: $OUT differs from generated output — re-run ./scripts/generate-copilot-instructions.sh" >&2
    rm -f "$TMP_OUT"
    exit 1
  fi
  echo "OK: $OUT in sync with $CONFIG"
  rm -f "$TMP_OUT"
  exit 0
fi

mkdir -p "$(dirname "$OUT")"
mv "$TMP_OUT" "$OUT"
echo "wrote $OUT from $CONFIG (${#RISKY_PATHS[@]} risky paths, floor ${COVERAGE_FLOOR}%)"
